Rails:
  Enabled: true

Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'Guardfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
